dependencies:
  - nbserverproxy
  - tornado <6
  - pyviz/label/dev::geoviews-core=1.6.2
  - pyviz/label/dev::holoviews=1.12.2
  - pyviz/label/dev::panel=0.5.1
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader
  - bokeh::bokeh
  - fastparquet
  - python-snappy